# Generated by Django 5.0.6 on 2024-08-09 13:17

import Post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=Post.models.get_post_picture_path, verbose_name='picture'),
        ),
    ]
