# Generated by Django 5.0.6 on 2024-08-09 12:06

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=User.models.get_avatar_picture_path),
        ),
    ]
