# Generated by Django 5.0.6 on 2024-08-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='things_user_likes',
            field=models.TextField(blank=True, verbose_name='Things User Likes'),
        ),
    ]
