# Generated by Django 5.0.6 on 2024-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_phone_number_user_things_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, null=True),
        ),
    ]
