# Generated by Django 5.0.6 on 2024-08-12 14:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='things_user_likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Things User Likes'),
        ),
    ]
